# Generated by Django 5.0.6 on 2024-05-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0002_matriculation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="cpf",
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="rg",
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
