# Generated by Django 5.0.6 on 2024-05-21 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0003_alter_student_cpf_alter_student_rg"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="phone",
            field=models.CharField(default="", max_length=15),
        ),
    ]
