# Generated by Django 5.0.6 on 2024-05-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0004_student_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="photo",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
